### ISSUE TITLE
keep getting errors

### ISSUE THREAD

**Issue by eliezergu** [Daplie/nodejs-self-signed-certificate-example#8]
i tried your approach several times i did everything correctly i tried all approache's you give and i kepp getting this err  >>>
    
        Generating RSA private key, 2048 bit long modulus
..........+++
................................................................................................+++
e is 65537 (0x10001)
Subject does not start with '/'.
problems making Certificate Request

fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'C:\Users\shulem\Documents\myWebRTCApp\nodejs-ssl-trusted-peer-example\certs\server\my-server.key.pem'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.<anonymous> (C:\Users\shulem\Documents\myWebRTCApp\nodejs-ssl-trusted-peer-example\serve.js:13:11)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)

module.js:471
    throw err;
    ^

Error: Cannot find module 'C:\Users\shulem\Documents\myWebRTCApp\nodejs-ssl-trusted-peer-example\request-without-warnings.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
 - without warnings, love node.js' https

 - without warnings, love cURL
test.sh: line 26: kill: (6452) - No such process

The most importent line is probably this >>> Subject does not start with '/'.
problems making Certificate Request

Becouse this is the one i'm getting when i try tom run step by step i'm getting stuck by this step >>>
   openssl req \
  -x509 \
  -new \
  -nodes \
  -key all/my-private-root-ca.key.pem \
  -days 1024 \
  -out all/my-private-root-ca.crt.pem \
  -subj "/C=US/ST=Utah/L=Provo/O=ACME Signing Authority Inc/CN=example.com"

i'm getting this err >>>   Subject does not start with '/'.
problems making Certificate Request

I tried this one too >>>
https://github.com/coolaj86/nodejs-ssl-trusted-peer-example

and i'm getting the same err's
PLEASE HELP ME SOLVE THE PROBLEM

**Comment by coolaj86** [comment]
Sounds like a problem on Windows that has to do with string and path escaping. I'll try it on my Surface Book in the morning.

**Comment by eliezergu** [comment]
did you try it on your surface?

**Comment by coolaj86** [comment]
Not yet. I'm actually at Microsoft Connect and I haven't had time yet to play with it, but it's on my todo.
